# project source
PROJ_SRC := 0-indefinite-hello.c 1-check-formats.c 2-bulk-transfer.c
PROJ_SRC += 3-char-echo.c 4-pi-echo.c 5-countdown-blink.c

# sets objs as the default directory for objects and creates it if
# it doesn't already exist
BUILD_DIR ?= objs
$(BUILD_DIR):
	@mkdir -p $@

LIB := lib

# adds lib/include to the list of directories to search
# through when resolving #include directives
INC := -I$(LIB)/include -I$(LIB)/libc

START_SRC := $(LIB)/start.S
START_OBJ := $(addprefix $(BUILD_DIR)/, $(patsubst %.S,%.o,$(START_SRC)))

# source files that each program depends on
COMMON_SRC := $(wildcard $(LIB)/src/*.[cS]) $(wildcard $(LIB)/libc/*.c) 

# object files that each program depends on
# addprefix prepends the build dir to the files
# patsubst substitutes the file suffix of stems with
# left suffix with right suffix
COMMON_OBJS := $(addprefix $(BUILD_DIR)/, \
				$(patsubst %.c,%.o,$(patsubst %.S,%.o,$(COMMON_SRC))))

ARCHIVE := $(BUILD_DIR)/$(LIB).a

# names of stripped binaries (from elfs -> binary)
progs := $(addprefix $(BUILD_DIR)/,$(PROJ_SRC:.c=.bin))

# 'list' files contain disassembled programs that are
# human-readable (from elf -> list)
lists := $(addprefix $(BUILD_DIR)/,$(PROJ_SRC:.c=.list))

# linked object files
elfs := $(addprefix $(BUILD_DIR)/,$(PROJ_SRC:.c=.elf))

# linker script that specifies memory layout of programs
LDSCRIPT := $(LIB)/memmap

# handle dependencies with `.d` files generated by the compiler;
# handles automatic recompilation when headers change
DEPS := $(COMMON_OBJS:.o=.d)
DEPS += $(addprefix $(BUILD_DIR)/,$(PROJ_SRC:.c=.d))
DEPS += $(START_OBJ:.o=.d)

# include the `.d` files directly, when they exist
-include $(DEPS)

# disable built-in rules which can result in unexpected results
.SUFFIXES:

# short-hand variables for compilation tools
ARM := arm-none-eabi
CC  := $(ARM)-gcc # C compiler
LD  := $(ARM)-ld # linker
AS  := $(ARM)-as # assembler
OD  := $(ARM)-objdump # used for disassembly
OCP := $(ARM)-objcopy # used to strip symbols from elf for final binary
AR  := $(ARM)-ar # used to create the lib.a archive from common source files

# architecture flags
# -march: specify machine architecture
# note that for ASFLAGS we add 'kz' to add more functionality for hand-written
# 	assembly; specifically:
# 		k-- multiprocessing extensions: adds exclusive load/store (LDREX/STREX)
# 			instructions for atomic operations
# 		z-- Security Extension (TrustZone): adds secure/non-secure worlds and
# 			instructions like `smc` to switch between them
# 		source: https://developer.arm.com/documentation/ddi0406/b/Application-Level-Architecture/Introduction-to-the-ARM-Architecture/Architecture-versions--profiles--and-variants
ARCH_FLAGS := -march=armv6

# dependency flags; these help Make help us
# -MMD: generate a `.d` dependency file from includes that only lists user
#  	headers (not system headers)
# -MP: add empty rules for each header in the `.d` file so Make doesn't break
#  	when a header and all references (i.e., #include) are deleted
# also including $(INC) here because both C and assembly files need them
DFLAGS := -MMD -MP $(INC)

# compiler flags
# note: order matters!
# -O: Optimize
# -Wall: enable several warnings
# -Wno-unused-variable: negates activiation of warning `Wunused-variable`
#  	enabled by `Wall`
# -Werror: make all warnings into errors
# -ffreestanding: assert that compilation targets a freestanding environment
# -std: specify C standard
CFLAGS := -O -Wall -Wno-unused-variable -Werror \
			-ffreestanding -std=gnu99 \
			$(ARCH_FLAGS) $(DFLAGS)

# assembler flags
# note: order matters!
# note: since we invoke the assembler via the compiler (because we want the
# 	preprocessor), we pass the flags this way with -Wa,<flag_0>,...,<flag_{n-1}>
# note: we send the architecture to GCC *and* the assembler via GCC; we do
# 	the former to prevent GCC from making wrong assumptions about the
# 	architecture during preprocessing, and we do the latter because it needs
# 	it
# --warn: don't supress warning messages or treat them as errors
# --fatal-warnings: treat warnings as errors
# -mcpu: specify machine cpu
# -march: specify machine architecture
ASFLAGS := -Wa,--warn,--fatal-warnings,-mcpu=arm1176jzf-s,$(ARCH_FLAGS)kz \
			$(ARCH_FLAGS) $(DFLAGS)

# linker flags
# -nostdlib: do not use standard system startup files or libraries when linking
#  -T: specify the linker script
LDFLAGS := -nostdlib $(ARCH_FLAGS) -T $(LDSCRIPT)

# make all blinkies
all: $(progs)

# build the static archive
$(ARCHIVE): $(COMMON_OBJS)
	@rm -f $@
	$(AR) crf $@ $(COMMON_OBJS)
	$(OD) -D $@ > $@.list	

# rules to generate binaries: \.[S|c] -> .o -> .elf -> .list
# 												|
# 												----> .bin

## linking step
## note: the archive is the last thing because it's the last thing the
## linker will see to resolve unresolved symbols
$(elfs): %.elf: %.o $(START_OBJ) $(ARCHIVE) $(LDSCRIPT)
	@mkdir -p $(dir $@)
	$(CC) $(START_OBJ) $< $(LDFLAGS) -o $@ $(ARCHIVE) 

## .elf -> .list
$(lists): %.list: %.elf
	@mkdir -p $(dir $@)
	$(OD) -D $< > $@

## .elf -> .bin
## the `notdir` strips the path from the file, leaving it in the root rather
## than placing in BUILD_DIR
$(progs): %.bin: %.list %.elf
	$(OCP) $*.elf -O binary $(notdir $@)

## the following notes apply to the following two rules:
## note: the -c flag tells the compiler to compile, but not link
## 	the source files
## note: the $(BUILD_DIR) prefix is explicitly used only on the left (here 
## 	and below) because the objects and source files are in different
##	directories; in the above rules, both dependencies and targets are
## 	in $(BUILD_DIR)

## .c -> .o
$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

## .S -> .o
$(BUILD_DIR)/%.o: %.S
	@mkdir -p $(dir $@)
	$(CC) -c $(ASFLAGS) $< -o $@

clean:
	rm -rf $(BUILD_DIR)
	rm -f *.bin

# tell the Make program that the specified targets aren't real files,
# so to not look for timestamps on them
.PHONY: all clean
